title: Marianski Lab
logo: /assets/img/Hunter_logo.png
description: Marianski Group at Hunter College
people_url: people.html
public_url: publications.html
resear_url: research.html
codede_url: code.html
contac_url: contact.html
show_downloads: False 
google_analytics: 
theme: jekyll-theme-minimal
